from fastapi import APIRouter

from app.api.routes import escrow, escrow_phase64, ledger, notifications, refunds, settlements, wallet
from app.api.v1 import admin_ai, admin_audit, admin_dashboard, admin_disputes, admin_emergency, admin_kyc, admin_support, admin_users, ai, ai_insights, auth, dashboard, emergency, forecasts, grid_ai, health, kyc, listings, marketplace, mock_listings, mock_purchases, pricing, purchases, recommendations, support, suspended_users, sustainability, user_marketplace, users

api_router = APIRouter()
api_router.include_router(health.router, tags=["health"])
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(marketplace.router, prefix="/marketplace", tags=["marketplace"])
api_router.include_router(listings.router, prefix="/listings", tags=["listings"])
api_router.include_router(purchases.router, prefix="/purchases", tags=["purchases"])
api_router.include_router(user_marketplace.router, prefix="/users/me", tags=["marketplace"])
api_router.include_router(wallet.router, prefix="/wallet", tags=["wallet"])
api_router.include_router(ledger.router, prefix="/ledger", tags=["ledger"])
api_router.include_router(escrow_phase64.router, prefix="/escrow", tags=["escrow"])
api_router.include_router(escrow.router, tags=["escrow"])
api_router.include_router(settlements.router, prefix="/settlements", tags=["settlements"])
api_router.include_router(refunds.router, prefix="/refunds", tags=["refunds"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(forecasts.router, prefix="/forecasts", tags=["forecasts"])
api_router.include_router(recommendations.router, prefix="/recommendations", tags=["recommendations"])
api_router.include_router(pricing.router, prefix="/pricing", tags=["pricing"])
api_router.include_router(sustainability.router, prefix="/sustainability", tags=["sustainability"])
api_router.include_router(ai.router, prefix="/ai", tags=["ai"])
api_router.include_router(ai_insights.router, prefix="/insights", tags=["insights"])
api_router.include_router(admin_dashboard.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_ai.router, prefix="/admin/ai", tags=["admin-ai"])
api_router.include_router(admin_users.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_disputes.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_audit.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_emergency.router, prefix="/admin/emergency", tags=["admin-emergency"])
api_router.include_router(admin_support.router, prefix="/admin", tags=["admin-support"])
api_router.include_router(emergency.router, prefix="/emergency", tags=["emergency"])
api_router.include_router(support.router, prefix="/support", tags=["support"])
api_router.include_router(kyc.router, prefix="/kyc", tags=["kyc"])
api_router.include_router(admin_kyc.router, prefix="/admin/kyc", tags=["admin-kyc"])
api_router.include_router(suspended_users.router, prefix="/admin/suspended", tags=["admin-suspended"])
api_router.include_router(grid_ai.router, prefix="/grid/ai", tags=["grid-ai"])
